### ISSUE TITLE
Support for Audit logs

### ISSUE THREAD

**Issue by shahharsh176** [Healthlane-Technologies/Zango#166]
### Description

Built-in support for audit logs to track changes made in the dynamic models and core models (e.g. AppUsers, UserRole, PolicyModel, etc.)

### Background

Audit logs are essential for maintaining transparency, accountability, and compliance with regulatory requirements. They provide a detailed record of user activities, data modifications, etc. 

### Feature Details

- audit log module to capture the changes made in dynamic models
- Integration with App Panel to display the audit log table with search, filter, and export functionality

Tasks:

- [ ] Required changes like audit -> auditlog rename and removal from enterprise folder
- [ ] working version to be deployed on dev server for testing
- [ ] Code Cleaning and code review points
- [ ] check for public tenant models

**Comment by kc-diabeat** [comment]
@shahharsh176 I think it would be useful to have audit logs of  all objects of the app (e.g. AppUsers, UserRole, PolicyModel, etc.) and not just the user defined models.

**Comment by shahharsh176** [comment]
@kc-diabeat the dev testing and integration testing are done. We are planning to deploy the working version to the Dev Server today and get it tested by the testing team, and parallely we will be working on the code cleaning and code review points.
