### ISSUE TITLE
Improve error Messages for ``ws_makemigration`` and ``ws_migrate`` commands

### ISSUE THREAD

**Issue by shahharsh176** [Healthlane-Technologies/Zango#170]
### Description

Improve error Messages for various scenarios in [ws_makemigration](https://docs.zelthy.com/docs/documentation/ddms/migrating-ddms#step-1-generate-migrations-with-ws_makemigration) and [ws_migrate](https://docs.zelthy.com/docs/documentation/ddms/migrating-ddms#step-2-apply-migrations-with-ws_migrate) commands

### Background

Both `ws_makemigration` and `ws_migrate` commands require arguments. When invalid values are passed as arguments, clear and informative error messages should be raised to guide users in resolving issues.

Please find the list of scenarios and error messages in the Feature Details sections

### Feature Details

Failure Scenarios

#### 1. Invalid app_name 

If an invalid `app_name` is supplied in the `ws_makemigration` or `ws_migrate` command, the following error message should be displayed:

```shell
The app name '{app_name provided by user}' provided as an argument is invalid. 
Please ensure that you have entered the correct app name and try again.
```

**Comment by AjaySDwivedi1** [comment]
Can I work on this?

**Comment by ChrisMcLernon** [comment]
https://github.com/Healthlane-Technologies/Zango/pull/258
