### ISSUE TITLE
Add custom pages for error code lke 403, 404, 500 for non-dev environment

### ISSUE THREAD

**Issue by shahharsh176** [Healthlane-Technologies/Zango#199]
### Description

Add custom pages for error codes like 403, 404, and 500 for non-development environments.

### Background

Currently, error pages (such as 404, 500, 502, etc.) are served with default templates, which may not provide the best user experience. We need to enhance this by adding custom error templates for these specific error codes in the non-development environment.

### Feature Details

- Create the custom template for the below error codes
        - 403 
        - 404
        - 500
- We can utilize Django handlers, such as https://docs.djangoproject.com/en/4.2/ref/urls/#handler400
- Initially, simple templates can be added for each error code, and the updated templates will be included in this issue.

From a development perspective, the required changes to implement custom templates for error codes can be made initially, and then the final templates will be updated accordingly.

**Comment by ise8933** [comment]
Hello! I would like to try to contribute to this. Can I be added to this?

**Comment by kc-diabeat** [comment]
Hi @JohnPaul-404 Thanks for your interest in this issue. I have assigned it to you. Please share the expected timeline. @shahharsh176 Pls share our existing html templates if they can be of use here.
