### ISSUE TITLE
Workflow for App Panel build generation

### ISSUE THREAD

**Issue by shahharsh176** [Healthlane-Technologies/Zango#214]
### Description
Implement a GitHub workflow to automate the generation of builds for the App Panel when changes are made to the frontend folder. This automation will ensure that the latest build is always available for the App Panel and minimize manual steps for developers and maintainers.

### Background
Our project requires frequent updates to the App Panel Frontend components. Currently, building and pushing new builds to the assets folder is a manual process. By automating this workflow, we can ensure consistency, reduce human errors, and accelerate the development process.

### Feature Details

**Trigger**: The workflow should be triggered upon creation or update of a pull request if there are any changes in the frontend folder.

**Actions**:
The workflow should generate a build with a unique identifier or timestamp.
The generated build should be pushed to the assets folder within the repository.

**Outcome**: The App Panel should render the latest build from the assets folder.

**Comment by Josecespedesant** [comment]
Hello! I would like to work in this issue

**Comment by shahharsh176** [comment]
@Josecespedesant Thank you for taking up this issue. Let us know if you want to have any discussion while you work on it.

**Comment by kc-diabeat** [comment]
HI @Josecespedesant Pls let us know if you are working on this issue and by when can we expect the PR. Do let us know in case you are not able to find time for this. We will then assign it to someone else. Thanks.

**Comment by Josecespedesant** [comment]
Hi! Yes, please expect it by EOW or before if that's okay, got carried away during the past week
