### ISSUE TITLE
Country code selection in user add and edit forms

### ISSUE THREAD

**Issue by kc-diabeat** [Healthlane-Technologies/Zango#262]
**Description**
The App Panel has a section for managing application users. Currently the Add and Edit forms have hardcoded country code as "+91" which cannot be modified.

**Feature**
The country code should be a selectable field anb the desired country can be selected by searching its name. Pls refer to the reference interaction below:
![ScreenRecording2024-06-14at3 52 20PM-ezgif com-video-to-gif-converter](https://github.com/Healthlane-Technologies/Zango/assets/12683350/937572ff-40c9-4728-bf94-82cdba1a4d61)

**Comment by shambhabya** [comment]
Can I work on this?

**Comment by deepakdinesh1123** [comment]
@shambhabya Please feel free to work on this issue. Before beginning, could you please outline the approach that you plan to take to solve this? Additionally, if you require any help or resources, let us know.

**Comment by rahil1202** [comment]
Hey @shambhabya, I am planning to implement a selectable country code field with search functionality using  `react-phone-input-2`.  libraries provide pre-built components that handle country selection and phone number input with country codes.

**Comment by shambhabya** [comment]
@rahil1202 Sure, go ahead if you want to

**Comment by deepakdinesh1123** [comment]
@rahil1202 In Zango, we ensure that both the backend and frontend use the same configuration options by sending these options from the backend.

This feature requires the backend to send a list of available countries and their phone number extensions, which the frontend will then use. Let me know if you'd like to implement both the backend and frontend for this, or if you'd prefer to implement just the frontend while I handle the backend.

**Comment by rahil1202** [comment]
@deepakdinesh1123 I'll update both frontend and backend. Thank you for clarification

**Comment by shahharsh176** [comment]
Hi @rahil1202  , did you get a chance to work on it?

**Comment by rahil1202** [comment]
@shahharsh176 I have updated the frontend will work on backend soon.
