### ISSUE TITLE
Simple API for creating AppUser for Objects

### ISSUE THREAD

**Issue by kc-diabeat** [Healthlane-Technologies/Zango#276]
**Background**
A common requirement while developing applications on Zango is to have AppUsers corresponding to the Objects created in the application. Currently, the process involves creating AppUser object programatically and then updating the app_objects attribute of the AppUser object with the object's user role and uuid. This is tedious and requires the application to know unnecessary internal details about the AppUser implementation. We should have a simple API for creating an AppUser corresponding to an Object.

**Proposed API Singature**
```python
user_obj, validation_error = object.create_user(name, email, password, user_role)

Validation: This object must not be attached to an already existing user.

**Comment by Yadavanurag13** [comment]
Hey, I would like to fix this issue. Please assign me

**Comment by deepakdinesh1123** [comment]
@Yadavanurag13 can you please give an overview of your solution for this issue?
