### ISSUE TITLE
App Panel: Auditlog table is breaking if there is no Timezone and Date-Time configured for the app

### ISSUE THREAD

**Issue by shahharsh176** [Healthlane-Technologies/Zango#287]
### Bug Description

If there is no timezone and Date-Time configured for the app, accessing Auditlogs from the App Panel breaks.

Ref:

<img width="1254" alt="image" src="https://github.com/Healthlane-Technologies/Zango/assets/22682748/e74834e9-046b-4de3-a98c-7241d4c26366">

<img width="1254" alt="image" src="https://github.com/Healthlane-Technologies/Zango/assets/22682748/6e6ead1e-c036-4bc0-937e-1e0aa7e12ba1">

**Comment by nanellooo** [comment]
I'd like to take a crack at this!

What kind of behavior should it have instead? As in: if no timezone or datetime are set, then use a specific default (either pulled from the host system's time or a pre-set default)? If they aren't set, prompt the user to set one rather than error?

**Comment by deepakdinesh1123** [comment]
@nanellooo Please feel free to take up this issue, we can use the systems host time if timezone is not specified, please let me know if you need any help in implementing this
